use_frameworks!

target 'Example' do
  pod 'Alamofire', '~> 5.2'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'PoliceUKNetworking', :path => '../'
  
  target 'PoliceUKNetworking-Tests' do
    inherit! :search_paths
  end
end
